name:                           coverage

on:                             [push]

jobs:
  test:
    name:                       coverage 
    runs-on:                    ubuntu-latest
    container: 
      image:                    paritytech/ink-ci-linux:tarpaulin
      options:                  --security-opt seccomp=unconfined
    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2

      # - name:                   Generate code coverage
      #   run: |
      #     cargo tarpaulin --verbose --all-features --workspace -t 120 --out Xml

      - name:                   Run cargo-tarpaulin
        uses:                   actions-rs/tarpaulin@v0.1
        with:
          args: '--verbose --all-features --workspace --timeout 220 --out Xml -- --test-threads 1'

      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v1
        with:
          token:                ${{secrets.CODECOV_TOKEN}} # not required for public repos
          fail_ci_if_error:     true
